name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with Docker
      run: |
        docker run --rm -v "${PWD}/build:/srv/slate/build" -v "${PWD}/source:/srv/slate/source" slatedocs/slate build

   # - name: Deploy to server
   #   run: |
   #     rsync -avz --delete ./build/ youruser@yourhost:/path/to/deploy

   #   env:
   #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    - name: Serve with Docker 
      if: always()
      run: |
        docker-compose up -d